version: 2

updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "18:00"
      timezone: "Europe/Berlin"

    groups:
      all-nuget-dependencies:
        applies-to: version-updates
        patterns:
          - "*"