name: IntegrateManifestExplorer

# Only executed on pull requests for the main branch.
on:
  pull_request:
    branches: [ main ]

# Workflow can 
#   * read repositroy content
#   * create and update GitHub Checks.
#   * comment on PRs, update PR statuses, or modify PR metadata.
permissions:
  contents: read
  checks: write
  pull-requests: write

# Prevents multiple runs of the same workflow from overlapping.
# If a new run starts for the same branch, GitHub automatically cancels the previous run.
concurrency:
  group: ci-explorer-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Build the application and run tests.
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code.
      - uses: actions/checkout@v4

      # Setup dotnet sdk.
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0'

      # Cache nuget references to speed up build.
      - name: Cache NuGet
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: nuget-${{ runner.os }}-pr
          restore-keys: |
            nuget-${{ runner.os }}-

      # Restore nuget.
      - name: Restore
        run: dotnet restore

      # Identify all csproj files
      - name: List project files
        if: always()
        run: find . -iname "*.csproj"

      # Build the manifest explorer.
      - name: Build
        run: dotnet build mqtt2otel.ManifestExplorer/mqtt2otel.ManifestExplorer/mqtt2otel.ManifestExplorer.csproj -c Release --no-restore -warnaserror

      # Build the test project
      - name: Build
        run: dotnet build mqtt2otel.ManifestExplorer.Tests/mqtt2otel.ManifestExplorer.Tests.csproj -c Release --no-restore -warnaserror
          
      # Installs the playwright browsers.
      - name: Install Playwright browsers
        run: pwsh bin/Release/net10.0/playwright.ps1 install --with-deps chromium
        working-directory: mqtt2otel.ManifestExplorer.Tests

      # Run tests and generate TestResults file.
      - name: Test
        env:
          OTEL_SERVICE_NAME: mqtt2otel-explorer-github-tests
          OTEL_SERVICE_NAMESPACE: mqtt2otel-github
          OTEL_EXPORTER_OTLP_ENDPOINT: https://ingress.europe-west4.gcp.dash0.com/
          OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
          OTEL_EXPORTER_OTLP_HEADERS: Authorization=Bearer ${{ secrets.DASH0_TOKEN }},Dash0-Dataset=default
        working-directory: mqtt2otel.ManifestExplorer.Tests/bin/Release/net10.0/
        run: ./mqtt2otel.ManifestExplorer.Tests --report-gh

      # Identify where the playwright trace files have been written to.
      - name: List trace files
        if: always()
        run: find . -iname "*.zip" -path "*traces*"

      # Upload Playwright traces, if existing. (Usually only available on failure, if not configured otherwise)
      - name: Upload Playwright Traces
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-traces
          path: ./mqtt2otel.ManifestExplorer.Tests/bin/Release/net10.0/playwright/traces/**
          if-no-files-found: ignore